# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:year/:month/:day/:title

# Setup
title:               'Lijiahao8898'
tagline:             'F2E'
description:         'make progress every day'
url:                 http://lanyon.getpoole.com
baseurl:             ''
plugins_dir:         [jekyll-paginate]
gems:                [jekyll-paginate]
paginate:            20
paginate_path:       "page:num"
# plugins:           [jekyll-paginate]

# About/contact
author:
  name:              lijiahao
  cname:             李家豪
  url:               https://lijiahao8898.io
  email:             '#'
  address:           cn
  github:            https://github.com/lijiahao8898

sass:                sass_dir: _sass

# Custom vars
version:             1.0.0
